trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'gpgtest-artifactory'
    cliInstallationRepo: 'jf-cli-remote'

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

